# Map topic
map_topic: /obstacle_map

# Footprint Topic (std_msgs/String)
robot_footprint_topic: /robot_footprint
# Default Footprint
#robot_footprint: "[[0.35,0.2],[0.35,-0.2],[-0.35,-0.2],[-0.35,0.2]]"
robot_footprint: "[[0.35,0.2],[0.35,-0.2],[0.21,-0.2],[0.21,-0.36],[-0.64,-0.36],[-0.64,0.36],[0.21,0.36],[0.21,0.2]]"
# robot_footprint: "[[0.35,0.2],[0.35,-0.2],[0.06,-0.2],[0.06,-0.33],[-0.64,-0.33],[-0.64,0.33],[0.06,0.33],[0.06,0.2]]"

# Velocity Input Topic
cmd_vel_input: /cmd_vel_muxed
# Velocity Output Topic
cmd_vel_output: /cmd_vel_safe

# Slowing time look ahead
slowing_look_ahead_time: 2
# Stopping time look ahead
stopping_look_ahead_time: 0.2
# Collision status reporting topic
collision_status: "collision_imminent"
# Collision avoidance enable topic 
avoidance_enable: "enable_avoidance"

# Indicator Light topic
indicator_topic: /tower_lights_cmd
mqtt_address: localhost
mqtt_topic: obstacle_proximity
mqtt_obstacle_safety_off_msg: safety_off
mqtt_obstacle_free_msg: clear
mqtt_imminent_collision_msg: imminent_collision
mqtt_near_collision_msg: near_collision

# Teleop Joy topic to Enable / Disable Collision Avoidance
joy_topic: /joy1/joy
# Enable / Sisable Button
enable_joy_button: 10
